language: python
os: linux
dist: bionic

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

git:
  depth: false

branches:
  only:
    - master
    - /^[0-9]+\.x$/
    - /^[0-9]+\.[0-9]+$/

addons:
  sonarcloud:
    organization: clarkperkins
    token:
      secure: "thxDw6g+PgwiWrCQ4pgStlU3wbT+Bn06kEHd3DMo1ck5pL+nj9EVwihJp6ToJ7LMV74HjB4Y0A5DREHzS1Uoq8VPWzUXyAAcIXzWxX/GFSDDTJeLqlIE4Z3JBhpMc0bmAkXh6/9vGCQHsNTIi5SpPaw8fs+Fd7jUOAnHsLzTwCU/1G45BHwz/aB7uxhA1XdB4rbGWKBtbxLppH9B7tH2lH1QXriB34BnzoOrcL8xbX231ss3cIINcDq+d13+WWUtR5NynT0g0lUYPXp52202O0Q4xSqpEQ/HCDfcjrBHsn1qguijjbv8pEaa4zpW87nw06VbFVfbY33j4v0AUr57b/K/QBcpI4rRnFk/PAcmkbIDi1luJ0UnhYnhdlFbltbe0qfEO2ZuBc3MGzBpf7lH2UbUfsvNx3AC0/GFaZbVsjluNh+1AZO5vcgGeMPVnS0751/OYhMByp0PpFUlkIQg2vgDAfaF4i/y1h1HF3p1Jvrx7U9BD45ep412LMEeFLGKZ2fqO70Z+xaiIGwyKJjhIMaLDxrSVe4+IshnK4iBltsl4P5vKv0a4REuQed/hhU2YaVX8csz+H4WGq+9+IuN2O3E4shmjzZYAhJj2oYcjv0MXSNpvRBZb0+jr6C1HDEjycPmMcWEj2ByjKYz8HWoDiFVd75ej6WTBUCNt9RyGAg="

install:
  - ./install.sh

script:
  - ./build.sh

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "XbaDvjIb1/Q7OZrmooEeq1a5lGT2ax5ivdOdw3jf4nGfDy6keFx4hGenBIjyiqmxUDB9GLaZ5gsPR5o/90hTKl8K0QIUducRlPCZF+RPT96+hYa3+cAwEDDDn6FhfLZKeTu+rKIENr4Bt6eSLPqPFDmoBOFeSe9eoGN8zMKh6QFheBp3a7V8eOf928KW4Qj/juW++Wv3cZ3oIU2y31jEZ+jAsDGMJzX4M01dwfszvHDSSToEgpPT2GK/Ccr4LeDiMVPz0rRPpfwK6dsh+bsitwMyO3JTtenEDXwINGuhu9S2f4ZYfkbRMuCeHYgFDioH3YWa8lSeUbaaJSKId3BIatf46E+fPhDcNGCx0sEIOls1W2ky12LZMCFSQ0R7FGPRHaxTrx9c9du6RF7gMAN9cXwwovfr46u5ShLPXwnS/L8oEAc/CNdGtcMttcwnfgFoET3jwo9XtK+zfTHeMTw5TeYqt/lOVvSpFO/VSh2pV8V9tnqKb0oRtzuo8trBS2d2srsESAH06RjjrlAv8sw2vIjrsBCoAdcQMjEGBhtqErBOIe2FC7YbC9Pe4RdTBo/GILEsXviUm02HHmyyZqYnN7tvUq4c+iWs9izfpA6yB3uaktF6R/CLSlSm45mkcijdd9EiASkgtIkBu3Hrn4K0gm/nXG5zyMyNRtbIxAgTE+E="
    distributions: sdist bdist_wheel
    edge: true
    on:
      tags: true
      repo: clarkperkins/click-shell
      python: '3.5'
